name: build vehicle and publish Docker image to ghcr.io

concurrency: production # allow maximum of one running and pending job

on:
  push:
    paths:
      - 'vehicle/**'
      - '.github/workflows/build.yaml'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-vehicle-and-docker-publish:
    name: Build vehicle
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    env:
      JAVA_VERSION: '21'
      JAVA_DISTRIBUTION: 'temurin'
      DOCKERFILE_LOCATION_NEW: './vehicle/target/'
      DOCKERFILE_LOCATION: './src/main/docker/Dockerfile'
      RUNNER_JAR_LOCATION: './target'
      PROJECT_LOCATION: './vehicle/'
      IMAGE_TAG: 'latest'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Build vehicle project with maven
        working-directory: ${{ env.PROJECT_LOCATION }}
        run: | # multi line string operator
          mvn clean package
          cp ${{ env.DOCKERFILE_LOCATION }} ${{ env.RUNNER_JAR_LOCATION }}

      - name: check Dockerfile
        working-directory: ${{ env.DOCKERFILE_LOCATION_NEW }}
        run: dir

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and publish Docker image
        run: |
          REPOSITORY=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')

          docker build --tag ghcr.io/$REPOSITORY:${{ env.IMAGE_TAG }} ${{ env.DOCKERFILE_LOCATION_NEW }}

          docker push ghcr.io/$REPOSITORY:${{ env.IMAGE_TAG }}
          
