name: deploy vehicle to leocloud

concurrency: production # allow maximum of one running and pending job

on:
  workflow_run:
    workflows: [ "build vehicle and publish Docker image to ghcr.io" ]
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-vehicle:
    name: deploy vehicle
    runs-on: ubuntu-24.04
    env:
      K8S_DEPLOYMENT_NAME: 'appsrv'

    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: deploy to cluster
        uses: ghostzero/kubectl@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout restart deployment ${{ env.K8S_DEPLOYMENT_NAME }}

